version: "3"

services:
  webserver:
    image: oberd/php-8.0-apache
    container_name: '${COMPOSE_PROJECT_NAME}-apps'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    depends_on:
      - database
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT-/var/www/html}
      ADMINER_PORT: ${HOST_MACHINE_ADMINER_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  database:
    build:
      context: "./mysql"
    container_name: '${COMPOSE_PROJECT_NAME}-mysql'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  adminer:
    image: adminer
    container_name: '${COMPOSE_PROJECT_NAME}-adminer'
    restart: 'always'
    depends_on:
      - database
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DEFAULT_DB_NAME: adminer
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - '${HOST_MACHINE_ADMINER_PORT}:8080'
  tests:
    image: "lehrermarktplatz/php-dev-test:latest"
    command: [ "-s", "basic" ]
    depends_on:
      - webserver
    environment:
      APP_HOST: "webserver"
      APP_PORT: "80"